### ISSUE TITLE
mise en place d'un serveur docker

### ISSUE THREAD

**Issue by Bastien-Helec** [Bastien-Helec/sae302#16]
Un contenaire qui va nous permettre de pouvoir faire chacun son travail de chaque coté pour pouvoir travailler ensuite la base de données et communiqué directement avec. Un documentation sera mis en place en dessous de cette issue

**Comment by Bastien-Helec** [comment]
# Package mis en place : 

- Mise en place du docker
- pour pourvoir le recuperer https://github.com/Bastien-Helec/sae302/pkgs/container/sae302
- quand une modification est faite faire un ``` docker push ghcr.io/username_github/sae302:0.[version]``` quand une grosse partie 
 du projet est terminer on incremente a 1 puis a 2 ...

**Comment by Bastien-Helec** [comment]
note a moi ajouter un readme pour permettre de pouvoir pull et push sans passer par la

**Comment by Bastien-Helec** [comment]
1. tu genere un token qui permet d'ecrire et de delete les packages
2. tu ecris dans ton CLI : 
3. ```
export $CR_PAT= [token]
```
5. tu continue avec :  
```
echo $CR_PAT | docker login ghcr.io -u [ton_username_github] --password-stdin 
```
ça te permet de te login avec docker et github 

6.

**Comment by Bastien-Helec** [comment]
Il me manque a voir pour faire l'envoi avec nouvelle configuration

**Comment by Bastien-Helec** [comment]
# commande pour ajouter en update les dockers : 

@ChatRall 

1.
```
docker pull ghcr.io/[username(si ça fonction pas tu mets : bastien-helec)]/sae302:[version]
```

2.
```
docker run -it ghcr.io/...
```

tu fais tes modifs 

3.
```
docker commit [container id]  ghcr.io/[username(si ça fonction pas tu mets : bastien-helec)]/sae302:[version]
```

4.
```
docker tag [la nouvelle image]  ghcr.io/[username(si ça fonction pas tu mets : bastien-helec)]/sae302:[version]
```
5.
```
docker push ghcr.io/[username(si ça fonction pas tu mets : bastien-helec)]/sae302:[version]
```

je te fais un fichiers complet quand j'ai le temps

**Comment by ChatRall** [comment]
Nickel tu peux merge

**Comment by ChatRall** [comment]
docker run -it django_mysql_setup_v1
