### ISSUE TITLE
Installation Django et configuration pour utiliser MySQL

### ISSUE THREAD

**Issue by ChatRall** [Bastien-Helec/sae302#22]

**Comment by ChatRall** [comment]
CR qui explique comment j'ai fait, utile pour refaire sur le main container.

[Django_MySQL_CR_Randall.pdf](https://github.com/Bastien-Helec/sae302/files/13386583/Django_MySQL_CR_Randall.pdf)

**Comment by Bastien-Helec** [comment]
@ChatRall j'ai besoin de ton installation docker je peux rien faire autrement
