### ISSUE TITLE
Conception de la Base de Données

### ISSUE THREAD

**Issue by ChatRall** [Bastien-Helec/sae302#23]
Création des tables via des Scripts Django (python manage.py shell) + Établissement des relations entre les tables. Directement en lien avec l'étape "Construction de Templates HTML et Interface Utilisateur".

**Comment by ChatRall** [comment]
Je créer des scripts qui inséreront des données dans ma base de données , ceux-ci se basant sur chaque modèle de données comme la création d'utilisateurs, de colis, de véhicules, et d'enregistrements de position GPS. Ces données seront affichées de différentes façon via les templates que je développe.

**Comment by Bastien-Helec** [comment]
est ce que tu peux me les mettres dans une branche s'il te plait et le commit que j'inspecte tout ça

**Comment by ChatRall** [comment]
Fait aujourd'hui (5/12/2023) : 
- Création des utilisateurs pour chaque rôle (expéditeur, transporteur, destinataire).
