### ISSUE TITLE
Construction de Templates HTML et Interface Utilisateur

### ISSUE THREAD

**Issue by ChatRall** [Bastien-Helec/sae302#27]
Création de templates pour chaque action utilisateur (création de colis, la mise à jour des positions GPS, la gestion des livraisons, et la confirmation de réception) intégrant des formulaires Django pour la saisie de données et des tableaux pour l'affichage.

**Comment by ChatRall** [comment]
J'ai déjà créé les templates en soit il me reste plus qu'à faire en sorte qu'elles répondent au mieux à l'application demandée.

**Comment by Bastien-Helec** [comment]
tiens regarder avec ça : https://docs.djangoproject.com/fr/2.2/topics/templates/

**Comment by ChatRall** [comment]
Je vais essayer de :
- Modifier mes templates HTML pour afficher dynamiquement les informations des colis, utilisateurs et véhicules.
- M'assurer que les formulaires de création de colis et de mise à jour des positions GPS fonctionnent correctement et mettent à jour les données dans la base de données.

**Comment by ChatRall** [comment]
Fait aujourd'hui : 
Back-end (front-end plus tard) : 
- Page de login
- Redirection des utilisateurs une fois connectés à leur page correspondante.

Reste à faire : 
- Implémenter dans chaque page les fonctionnalités spécifiques des utilisateurs correspondants (Expéditeur, Transporteur, Destinataire, pas Root car simplement redirection vers interface admin) conformément au cahier des charges.
