### ISSUE TITLE
Droits des utilisateurs

### ISSUE THREAD

**Issue by Bastien-Helec** [Bastien-Helec/sae302#8]
Mise en places des droits pour 2 ou 1 compte des droits administrateurs
puis le reste en droits uniquement sur sont propres compte : 
- modification de c'est données personnelles
- Ajouter le role du compte dans un field de SQL

**Comment by ChatRall** [comment]
Les permissions sont assignés à chaque groupe d'utilisateur (Expéditeur, Transporteur, Destinataire, Root), reste à les implémenter intelligemment dans leur page web correspondante.
